name: ShipZen
description: A companion action for ShipZen

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: 'npm'

    - run: npx tsx ./src/index.ts
      id: update
      shell: bash

    - uses: peter-evans/create-pull-request@v6
      with:
        commit-message: "Update ShipZen"
        branch: shipzen-update
        title: ${{ steps.update.outputs.title }}
        body: ${{ steps.update.outputs.body }}
        delete-branch: true
